Write-Host "Video-only production transport milestone"
Write-Host "Goal: run GStreamer webcam capture into WebRTC transport"
Write-Host "Use edge_client/configs/edge_client.yaml for parameters"
Write-Host "First implementation target:"
Write-Host "- webcam capture"
Write-Host "- 640x480"
Write-Host "- 15 FPS"
Write-Host "- shallow queue"
Write-Host "- WebRTC via webrtcsink"