runtime:
  enable_legacy_gst_video_bridge: false
  signaling_host: "141.210.144.85"
  signaling_port: 8443
  signaling_use_tls: false

tasks:
  emotion_recognition:
    active_backend: emotion_emotieff
    backends:
      emotion_hse:
        url: http://emotion_hse:8001
      emotion_emotieff:
        url: http://emotion_emotieff:8002

  speech_recognition:
    active_backend: asr_riva
    backends:
      asr_riva:
        url: http://asr_riva:8003

  object_detection:
    active_backend: null
    backends: {}

  gesture_recognition:
    active_backend: null
    backends: {}